# fly.toml app configuration file generated for libri on 2026-10-04T18:03:00+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'libri'
primary_region = 'lhr'

[build]
  dockerfile = 'Dockerfile'

[env]
  COOKIE_SAMESITE = 'lax'
  COOKIE_SECURE = '1'
  DB_PATH = '/data/book_rec.db'

[[mounts]]
  source = 'book_data'
  destination = '/data'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'suspend'
  auto_start_machines = true
  min_machines_running = 0

  [[http_service.checks]]
    interval = '30s'
    timeout = '5s'
    grace_period = '10s'
    method = 'GET'
    path = '/'

[[vm]]
  size = 'shared-cpu-1x'
  memory = '512mb'
  cpus = 1
  memory_mb = 512
